FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /repo
WORKDIR /repo/algorithms/C++/BitapAlgorithm
RUN g++ -o bitap Bitap.cpp

FROM ubuntu:22.04 as package
COPY --from=builder /repo/algorithms/C++/BitapAlgorithm/bitap /
