FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /repo
WORKDIR /repo/algorithms/C++/BitapAlgorithm
RUN g++ -o bitap Bitap.cpp
